name: CI/CD Taximetro

on:

  push:

    branches: [ "main", "develop" ] 
 
  workflow_dispatch:

env:
  
  # ghcr.io = almacen de imagenes de github
  REGISTRY: ghcr.io
   
jobs:

  # ===  TESTEAR LA APP ===
  test-app:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Bajar código
        uses: actions/checkout@v4
      
      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # Versión 3.11 es el que esta en Dockerfile

      #  Instalamos las librerías necesarias.
      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Ejecutar Tests
        run: python -m unittest discover -s . -p "test_*.py"

  build-and-push:
    
    needs: test-app
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write 

    steps:
      
      - name: Bajar código
        uses: actions/checkout@v4

      - name: Convertir nombre a minúsculas
        run: |
          # ${GITHUB_REPOSITORY,,} es un comando de Linux que pasa todo a minúsculas.
          
          echo "IMAGE_NAME=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
      
      - name: Loguearse en GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generar etiquetas Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch     # Etiqueta con el nombre de la rama
            
      
      - name: Construir y Subir
        uses: docker/build-push-action@v5
        with:
          context: .                  # El Dockerfile está aquí mismo (.)
          push: true                  # Súbela al registro
          tags: ${{ steps.meta.outputs.tags }}     # Usa las etiquetas generadas antes
          labels: ${{ steps.meta.outputs.labels }}